name: Deploy to Local Webserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: SSH Deployment
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add SSH Key to Known Hosts
      run: ssh-keyscan -H ssh.abbie.dev >> ~/.ssh/known_hosts

    - name: Deploy to Local Webserver
      run: |
        ssh abbie@ssh.abbie.dev 'cd ~/Git/gitprofile-fork && git pull origin main && source ~/.bashrc && bash deploy.sh'
